apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : ipn-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: dev
  source:
    path   : "HelmCharts/Ipn-controller"
    repoURL: "git@github.com:inbmonitoring/cicd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: bahaterenko/ipn-controller:468728e

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false 
