apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    chart: keycloak
    targetRevision: 24.2.0
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: keycloak
      values: |
       auth:
        adminUser: admin
        adminPassword: 44000-monkeys 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keykl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
