apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    chart: keycloak
    targetRevision: 26.0.8
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: keycloak
      valueFiles:
      - https://raw.githubusercontent.com/vvya2000/cicd/refs/heads/main/apps/keycloak/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keykl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
