apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    chart: keycloak
    targetRevision: 24.0.4
    repoURL: oci://registry-1.docker.io/bitnamicharts/keycloak
    helm:
      releaseName: keycloak
      valueFiles:
      - https://raw.githubusercontent.com/vvya2000/cicd/refs/heads/main/apps/keycloak/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keykl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
