apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    chart: keycloak
    targetRevision: 24.2.0
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: keycloak
      values: |
       global:
        defaultStorageClass: local-storage
       auth:
        adminUser: admin
        adminPassword: 44000-monkeys 
       ingress:
        enabled: true
        hostname: keycloak.local
        servicePort: https
        tls: true
        selfSigned: true
        
  destination:
    name: in-cluster
    namespace: keykl
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
