apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: dev
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name      : {{ .Release.Name }}-3000
      protocol  : TCP
      port      : 3000
      targetPort: 3000
    - name      : {{ .Release.Name }}
      protocol  : TCP
      port      : 3001
      targetPort: 3001
    - name      : {{ .Release.Name }}-3002
      protocol  : TCP
      port      : 3002
      targetPort: 3002
    - name      : {{ .Release.Name }}-3003
      protocol  : TCP
      port      : 3003
      targetPort: 3003
    - name      : {{ .Release.Name }}-control-api
      protocol  : TCP
      port      : 3004
      targetPort: 3004
    - name      : {{ .Release.Name }}-3005
      protocol  : TCP
      port      : 3005
      targetPort: 3005      
